version: '3'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: k_on
      MYSQL_ROOT_PASSWORD: pass
      TZ: Asia/Tokyo
    ports:
      - 3307:3306
    volumes:
      - mysqldb:/var/lib/mysql:cached
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysqldb:
    driver: local
